# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2adf2aef12badcbcea0fab0824180d9b705dcae592c3a67eda84f1799a480c282d02be56e08c215da838c110df9a1638594fdceccb47d82409332cfcdaf49874

test:
  secret_key_base: 48199ab50e4901a891fd6de04fd105853bbf99a9b276dc035e909b2dc3835d577dc29369f1cf70dbbad601ea68cf559d39b4fe12f9ed54334a40117431c20197

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
